name: Build & Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  BE_Review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: packages/mercer-vip-main-be/node_modules
          key: be-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Login to GitHub Container Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install
        run: cd packages/mercer-vip-main-be && npm i --legacy-peer-deps

      - name: Lint errors
        run: cd packages/mercer-vip-main-be && npm run lint:errors

      - name: Test
        run: cd packages/mercer-vip-main-be && npm run test

  API_Review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm

      - name: Install
        run: npm i

      - name: Run linter
        run: npm run lint

      - name: Run Tests
        run: npm run test:coverage
